package;

enum abstract Scancode(Int) from Int to Int {
    var UNKNOWN = 0;
    var A = 4;
    var B = 5;
    var C = 6;
    var D = 7;
    var E = 8;
    var F = 9;
    var G = 10;
    var H = 11;
    var I = 12;
    var J = 13;
    var K = 14;
    var L = 15;
    var M = 16;
    var N = 17;
    var O = 18;
    var P = 19;
    var Q = 20;
    var R = 21;
    var S = 22;
    var T = 23;
    var U = 24;
    var V = 25;
    var W = 26;
    var X = 27;
    var Y = 28;
    var Z = 29;
    var KEY_1 = 30;
    var KEY_2 = 31;
    var KEY_3 = 32;
    var KEY_4 = 33;
    var KEY_5 = 34;
    var KEY_6 = 35;
    var KEY_7 = 36;
    var KEY_8 = 37;
    var KEY_9 = 38;
    var KEY_0 = 39;
    var RETURN = 40;
    var ESCAPE = 41;
    var BACKSPACE = 42;
    var TAB = 43;
    var SPACE = 44;
    var MINUS = 45;
    var EQUALS = 46;
    var LEFTBRACKET = 47;
    var RIGHTBRACKET = 48;
    var BACKSLASH = 49;
    var NONUSHASH = 50;
    var SEMICOLON = 51;
    var APOSTROPHE = 52;
    var GRAVE = 53;
    var COMMA = 54;
    var PERIOD = 55;
    var SLASH = 56;
    var CAPSLOCK = 57;
    var F1 = 58;
    var F2 = 59;
    var F3 = 60;
    var F4 = 61;
    var F5 = 62;
    var F6 = 63;
    var F7 = 64;
    var F8 = 65;
    var F9 = 66;
    var F10 = 67;
    var F11 = 68;
    var F12 = 69;
    var PRINTSCREEN = 70;
    var SCROLLLOCK = 71;
    var PAUSE = 72;
    var INSERT = 73;
    var HOME = 74;
    var PAGEUP = 75;
    var DELETE = 76;
    var END = 77;
    var PAGEDOWN = 78;
    var RIGHT = 79;
    var LEFT = 80;
    var DOWN = 81;
    var UP = 82;
    var NUMLOCKCLEAR = 83;
    var KP_DIVIDE = 84;
    var KP_MULTIPLY = 85;
    var KP_MINUS = 86;
    var KP_PLUS = 87;
    var KP_ENTER = 88;
    var KP_1 = 89;
    var KP_2 = 90;
    var KP_3 = 91;
    var KP_4 = 92;
    var KP_5 = 93;
    var KP_6 = 94;
    var KP_7 = 95;
    var KP_8 = 96;
    var KP_9 = 97;
    var KP_0 = 98;
    var KP_PERIOD = 99;
    var NONUSBACKSLASH = 100;
    var APPLICATION = 101;
    var POWER = 102;
    var KP_EQUALS = 103;
    var F13 = 104;
    var F14 = 105;
    var F15 = 106;
    var F16 = 107;
    var F17 = 108;
    var F18 = 109;
    var F19 = 110;
    var F20 = 111;
    var F21 = 112;
    var F22 = 113;
    var F23 = 114;
    var F24 = 115;
    var EXECUTE = 116;
    var HELP = 117;
    var MENU = 118;
    var SELECT = 119;
    var STOP = 120;
    var AGAIN = 121;
    var UNDO = 122;
    var CUT = 123;
    var COPY = 124;
    var PASTE = 125;
    var FIND = 126;
    var MUTE = 127;
    var VOLUMEUP = 128;
    var VOLUMEDOWN = 129;
    var KP_COMMA = 133;
    var KP_EQUALSAS400 = 134;
    var INTERNATIONAL1 = 135;
    var INTERNATIONAL2 = 136;
    var INTERNATIONAL3 = 137;
    var INTERNATIONAL4 = 138;
    var INTERNATIONAL5 = 139;
    var INTERNATIONAL6 = 140;
    var INTERNATIONAL7 = 141;
    var INTERNATIONAL8 = 142;
    var INTERNATIONAL9 = 143;
    var LANG1 = 144;
    var LANG2 = 145;
    var LANG3 = 146;
    var LANG4 = 147;
    var LANG5 = 148;
    var LANG6 = 149;
    var LANG7 = 150;
    var LANG8 = 151;
    var LANG9 = 152;
    var ALTERASE = 153;
    var SYSREQ = 154;
    var CANCEL = 155;
    var CLEAR = 156;
    var PRIOR = 157;
    var RETURN2 = 158;
    var SEPARATOR = 159;
    var OUT = 160;
    var OPER = 161;
    var CLEARAGAIN = 162;
    var CRSEL = 163;
    var EXSEL = 164;
    var KP_00 = 176;
    var KP_000 = 177;
    var THOUSANDSSEPARATOR = 178;
    var DECIMALSEPARATOR = 179;
    var CURRENCYUNIT = 180;
    var CURRENCYSUBUNIT = 181;
    var KP_LEFTPAREN = 182;
    var KP_RIGHTPAREN = 183;
    var KP_LEFTBRACE = 184;
    var KP_RIGHTBRACE = 185;
    var KP_TAB = 186;
    var KP_BACKSPACE = 187;
    var KP_A = 188;
    var KP_B = 189;
    var KP_C = 190;
    var KP_D = 191;
    var KP_E = 192;
    var KP_F = 193;
    var KP_XOR = 194;
    var KP_POWER = 195;
    var KP_PERCENT = 196;
    var KP_LESS = 197;
    var KP_GREATER = 198;
    var KP_AMPERSAND = 199;
    var KP_DBLAMPERSAND = 200;
    var KP_VERTICALBAR = 201;
    var KP_DBLVERTICALBAR = 202;
    var KP_COLON = 203;
    var KP_HASH = 204;
    var KP_SPACE = 205;
    var KP_AT = 206;
    var KP_EXCLAM = 207;
    var KP_MEMSTORE = 208;
    var KP_MEMRECALL = 209;
    var KP_MEMCLEAR = 210;
    var KP_MEMADD = 211;
    var KP_MEMSUBTRACT = 212;
    var KP_MEMMULTIPLY = 213;
    var KP_MEMDIVIDE = 214;
    var KP_PLUSMINUS = 215;
    var KP_CLEAR = 216;
    var KP_CLEARENTRY = 217;
    var KP_BINARY = 218;
    var KP_OCTAL = 219;
    var KP_DECIMAL = 220;
    var KP_HEXADECIMAL = 221;
    var LCTRL = 224;
    var LSHIFT = 225;
    var LALT = 226;
    var LGUI = 227;
    var RCTRL = 228;
    var RSHIFT = 229;
    var RALT = 230;
    var RGUI = 231;
    var MODE = 257;
    var SLEEP = 258;
    var WAKE = 259;
    var CHANNEL_INCREMENT = 260;
    var CHANNEL_DECREMENT = 261;
    var MEDIA_PLAY = 262;
    var MEDIA_PAUSE = 263;
    var MEDIA_RECORD = 264;
    var MEDIA_FAST_FORWARD = 265;
    var MEDIA_REWIND = 266;
    var MEDIA_NEXT_TRACK = 267;
    var MEDIA_PREVIOUS_TRACK = 268;
    var MEDIA_STOP = 269;
    var MEDIA_EJECT = 270;
    var MEDIA_PLAY_PAUSE = 271;
    var MEDIA_SELECT = 272;
    var AC_NEW = 273;
    var AC_OPEN = 274;
    var AC_CLOSE = 275;
    var AC_EXIT = 276;
    var AC_SAVE = 277;
    var AC_PRINT = 278;
    var AC_PROPERTIES = 279;
    var AC_SEARCH = 280;
    var AC_HOME = 281;
    var AC_BACK = 282;
    var AC_FORWARD = 283;
    var AC_STOP = 284;
    var AC_REFRESH = 285;
    var AC_BOOKMARKS = 286;
    var SOFTLEFT = 287;
    var SOFTRIGHT = 288;
    var CALL = 289;
    var ENDCALL = 290;
    //var RESERVED = 400;
    //var COUNT = 512;

    public static function fromWebCode(code:String):Scancode {
        return switch (code) {
            // Letters
            case "KeyA": A;
            case "KeyB": B;
            case "KeyC": C;
            case "KeyD": D;
            case "KeyE": E;
            case "KeyF": F;
            case "KeyG": G;
            case "KeyH": H;
            case "KeyI": I;
            case "KeyJ": J;
            case "KeyK": K;
            case "KeyL": L;
            case "KeyM": M;
            case "KeyN": N;
            case "KeyO": O;
            case "KeyP": P;
            case "KeyQ": Q;
            case "KeyR": R;
            case "KeyS": S;
            case "KeyT": T;
            case "KeyU": U;
            case "KeyV": V;
            case "KeyW": W;
            case "KeyX": X;
            case "KeyY": Y;
            case "KeyZ": Z;
            // Top-row digits
            case "Digit1": KEY_1;
            case "Digit2": KEY_2;
            case "Digit3": KEY_3;
            case "Digit4": KEY_4;
            case "Digit5": KEY_5;
            case "Digit6": KEY_6;
            case "Digit7": KEY_7;
            case "Digit8": KEY_8;
            case "Digit9": KEY_9;
            case "Digit0": KEY_0;
            // Control / editing
            case "Enter":        RETURN;
            case "Escape":       ESCAPE;
            case "Backspace":    BACKSPACE;
            case "Tab":          TAB;
            case "Space":        SPACE;
            case "Minus":        MINUS;
            case "Equal":        EQUALS;
            case "BracketLeft":  LEFTBRACKET;
            case "BracketRight": RIGHTBRACKET;
            case "Backslash":    BACKSLASH;
            case "Semicolon":    SEMICOLON;
            case "Quote":        APOSTROPHE;
            case "Backquote":    GRAVE;
            case "Comma":        COMMA;
            case "Period":       PERIOD;
            case "Slash":        SLASH;
            case "CapsLock":     CAPSLOCK;
            // Function keys
            case "F1":  F1;
            case "F2":  F2;
            case "F3":  F3;
            case "F4":  F4;
            case "F5":  F5;
            case "F6":  F6;
            case "F7":  F7;
            case "F8":  F8;
            case "F9":  F9;
            case "F10": F10;
            case "F11": F11;
            case "F12": F12;
            case "F13": F13;
            case "F14": F14;
            case "F15": F15;
            case "F16": F16;
            case "F17": F17;
            case "F18": F18;
            case "F19": F19;
            case "F20": F20;
            case "F21": F21;
            case "F22": F22;
            case "F23": F23;
            case "F24": F24;
            // Navigation cluster
            case "PrintScreen": PRINTSCREEN;
            case "ScrollLock":  SCROLLLOCK;
            case "Pause":       PAUSE;
            case "Insert":      INSERT;
            case "Home":        HOME;
            case "PageUp":      PAGEUP;
            case "Delete":      DELETE;
            case "End":         END;
            case "PageDown":    PAGEDOWN;
            case "ArrowRight":  RIGHT;
            case "ArrowLeft":   LEFT;
            case "ArrowDown":   DOWN;
            case "ArrowUp":     UP;
            // Numpad
            case "NumLock":        NUMLOCKCLEAR;
            case "NumpadDivide":   KP_DIVIDE;
            case "NumpadMultiply": KP_MULTIPLY;
            case "NumpadSubtract": KP_MINUS;
            case "NumpadAdd":      KP_PLUS;
            case "NumpadEnter":    KP_ENTER;
            case "Numpad1":        KP_1;
            case "Numpad2":        KP_2;
            case "Numpad3":        KP_3;
            case "Numpad4":        KP_4;
            case "Numpad5":        KP_5;
            case "Numpad6":        KP_6;
            case "Numpad7":        KP_7;
            case "Numpad8":        KP_8;
            case "Numpad9":        KP_9;
            case "Numpad0":        KP_0;
            case "NumpadDecimal":  KP_PERIOD;
            case "NumpadEqual":    KP_EQUALS;
            case "NumpadComma":    KP_COMMA;
            // Modifiers
            case "ShiftLeft":    LSHIFT;
            case "ShiftRight":   RSHIFT;
            case "ControlLeft":  LCTRL;
            case "ControlRight": RCTRL;
            case "AltLeft":      LALT;
            case "AltRight":     RALT;
            case "MetaLeft":     LGUI;
            case "MetaRight":    RGUI;
            // Misc
            case "ContextMenu":  APPLICATION;
            default:             UNKNOWN;
        }
    }

    public static function toString(scancode:Scancode):String {
        return switch (scancode) {
            case UNKNOWN: "Unknown";
            case A: "A";
            case B: "B";
            case C: "C";
            case D: "D";
            case E: "E";
            case F: "F";
            case G: "G";
            case H: "H";
            case I: "I";
            case J: "J";
            case K: "K";
            case L: "L";
            case M: "M";
            case N: "N";
            case O: "O";
            case P: "P";
            case Q: "Q";
            case R: "R";
            case S: "S";
            case T: "T";
            case U: "U";
            case V: "V";
            case W: "W";
            case X: "X";
            case Y: "Y";
            case Z: "Z";
            case KEY_1: "1";
            case KEY_2: "2";
            case KEY_3: "3";
            case KEY_4: "4";
            case KEY_5: "5";
            case KEY_6: "6";
            case KEY_7: "7";
            case KEY_8: "8";
            case KEY_9: "9";
            case KEY_0: "0";
            case RETURN: "Enter";
            case ESCAPE: "Escape";
            case BACKSPACE: "Backspace";
            case TAB: "Tab";
            case SPACE: "Space";
            case MINUS: "-";
            case EQUALS: "=";
            case LEFTBRACKET: "[";
            case RIGHTBRACKET: "]";
            case BACKSLASH: "\\";
            case NONUSHASH: "Non-US #";
            case SEMICOLON: ";";
            case APOSTROPHE: "'";
            case GRAVE: "`";
            case COMMA: ",";
            case PERIOD: ".";
            case SLASH: "/";
            case CAPSLOCK: "Caps Lock";
            case F1: "F1";
            case F2: "F2";
            case F3: "F3";
            case F4: "F4";
            case F5: "F5";
            case F6: "F6";
            case F7: "F7";
            case F8: "F8";
            case F9: "F9";
            case F10: "F10";
            case F11: "F11";
            case F12: "F12";
            case F13: "F13";
            case F14: "F14";
            case F15: "F15";
            case F16: "F16";
            case F17: "F17";
            case F18: "F18";
            case F19: "F19";
            case F20: "F20";
            case F21: "F21";
            case F22: "F22";
            case F23: "F23";
            case F24: "F24";
            case PRINTSCREEN: "Print Screen";
            case SCROLLLOCK: "Scroll Lock";
            case PAUSE: "Pause";
            case INSERT: "Insert";
            case HOME: "Home";
            case PAGEUP: "Page Up";
            case DELETE: "Delete";
            case END: "End";
            case PAGEDOWN: "Page Down";
            case RIGHT: "Right Arrow";
            case LEFT: "Left Arrow";
            case DOWN: "Down Arrow";
            case UP: "Up Arrow";
            case NUMLOCKCLEAR: "Num Lock";
            case KP_DIVIDE: "Numpad /";
            case KP_MULTIPLY: "Numpad *";
            case KP_MINUS: "Numpad -";
            case KP_PLUS: "Numpad +";
            case KP_ENTER: "Numpad Enter";
            case KP_1: "Numpad 1";
            case KP_2: "Numpad 2";
            case KP_3: "Numpad 3";
            case KP_4: "Numpad 4";
            case KP_5: "Numpad 5";
            case KP_6: "Numpad 6";
            case KP_7: "Numpad 7";
            case KP_8: "Numpad 8";
            case KP_9: "Numpad 9";
            case KP_0: "Numpad 0";
            case KP_PERIOD: "Numpad .";
            case NONUSBACKSLASH: "Non-US \\";
            case APPLICATION: "Application";
            case POWER: "Power";
            case KP_EQUALS: "Numpad =";
            case EXECUTE: "Execute";
            case HELP: "Help";
            case MENU: "Menu";
            case SELECT: "Select";
            case STOP: "Stop";
            case AGAIN: "Again";
            case UNDO: "Undo";
            case CUT: "Cut";
            case COPY: "Copy";
            case PASTE: "Paste";
            case FIND: "Find";
            case MUTE: "Mute";
            case VOLUMEUP: "Volume Up";
            case VOLUMEDOWN: "Volume Down";
            case KP_COMMA: "Numpad ,";
            case KP_EQUALSAS400: "Numpad = (AS400)";
            case INTERNATIONAL1: "International 1";
            case INTERNATIONAL2: "International 2";
            case INTERNATIONAL3: "International 3";
            case INTERNATIONAL4: "International 4";
            case INTERNATIONAL5: "International 5";
            case INTERNATIONAL6: "International 6";
            case INTERNATIONAL7: "International 7";
            case INTERNATIONAL8: "International 8";
            case INTERNATIONAL9: "International 9";
            case LANG1: "Language 1";
            case LANG2: "Language 2";
            case LANG3: "Language 3";
            case LANG4: "Language 4";
            case LANG5: "Language 5";
            case LANG6: "Language 6";
            case LANG7: "Language 7";
            case LANG8: "Language 8";
            case LANG9: "Language 9";
            case ALTERASE: "Alt Erase";
            case SYSREQ: "SysReq";
            case CANCEL: "Cancel";
            case CLEAR: "Clear";
            case PRIOR: "Prior";
            case RETURN2: "Return2";
            case SEPARATOR: "Separator";
            case OUT: "Out";
            case OPER: "Oper";
            case CLEARAGAIN: "Clear/Again";
            case CRSEL: "CrSel";
            case EXSEL: "ExSel";
            case KP_00: "Numpad 00";
            case KP_000: "Numpad 000";
            case THOUSANDSSEPARATOR: "Thousands Separator";
            case DECIMALSEPARATOR: "Decimal Separator";
            case CURRENCYUNIT: "Currency Unit";
            case CURRENCYSUBUNIT: "Currency Subunit";
            case KP_LEFTPAREN: "Numpad (";
            case KP_RIGHTPAREN: "Numpad )";
            case KP_LEFTBRACE: "Numpad {";
            case KP_RIGHTBRACE: "Numpad }";
            case KP_TAB: "Numpad Tab";
            case KP_BACKSPACE: "Numpad Backspace";
            case KP_A: "Numpad A";
            case KP_B: "Numpad B";
            case KP_C: "Numpad C";
            case KP_D: "Numpad D";
            case KP_E: "Numpad E";
            case KP_F: "Numpad F";
            case KP_XOR: "Numpad XOR";
            case KP_POWER: "Numpad ^";
            case KP_PERCENT: "Numpad %";
            case KP_LESS: "Numpad <";
            case KP_GREATER: "Numpad >";
            case KP_AMPERSAND: "Numpad &";
            case KP_DBLAMPERSAND: "Numpad &&";
            case KP_VERTICALBAR: "Numpad |";
            case KP_DBLVERTICALBAR: "Numpad ||";
            case KP_COLON: "Numpad :";
            case KP_HASH: "Numpad #";
            case KP_SPACE: "Numpad Space";
            case KP_AT: "Numpad @";
            case KP_EXCLAM: "Numpad !";
            case KP_MEMSTORE: "Numpad Mem Store";
            case KP_MEMRECALL: "Numpad Mem Recall";
            case KP_MEMCLEAR: "Numpad Mem Clear";
            case KP_MEMADD: "Numpad Mem +";
            case KP_MEMSUBTRACT: "Numpad Mem -";
            case KP_MEMMULTIPLY: "Numpad Mem *";
            case KP_MEMDIVIDE: "Numpad Mem /";
            case KP_PLUSMINUS: "Numpad ±";
            case KP_CLEAR: "Numpad Clear";
            case KP_CLEARENTRY: "Numpad Clear Entry";
            case KP_BINARY: "Numpad Binary";
            case KP_OCTAL: "Numpad Octal";
            case KP_DECIMAL: "Numpad Decimal";
            case KP_HEXADECIMAL: "Numpad Hexadecimal";
            case LCTRL: "Left Ctrl";
            case LSHIFT: "Left Shift";
            case LALT: "Left Alt";
            case LGUI: "Left Super";
            case RCTRL: "Right Ctrl";
            case RSHIFT: "Right Shift";
            case RALT: "Right Alt";
            case RGUI: "Right Super";
            case MODE: "Mode";
            case SLEEP: "Sleep";
            case WAKE: "Wake";
            case CHANNEL_INCREMENT: "Channel +";
            case CHANNEL_DECREMENT: "Channel -";
            case MEDIA_PLAY: "Media Play";
            case MEDIA_PAUSE: "Media Pause";
            case MEDIA_RECORD: "Media Record";
            case MEDIA_FAST_FORWARD: "Media Fast Forward";
            case MEDIA_REWIND: "Media Rewind";
            case MEDIA_NEXT_TRACK: "Media Next Track";
            case MEDIA_PREVIOUS_TRACK: "Media Previous Track";
            case MEDIA_STOP: "Media Stop";
            case MEDIA_EJECT: "Media Eject";
            case MEDIA_PLAY_PAUSE: "Media Play/Pause";
            case MEDIA_SELECT: "Media Select";
            case AC_NEW: "AC New";
            case AC_OPEN: "AC Open";
            case AC_CLOSE: "AC Close";
            case AC_EXIT: "AC Exit";
            case AC_SAVE: "AC Save";
            case AC_PRINT: "AC Print";
            case AC_PROPERTIES: "AC Properties";
            case AC_SEARCH: "AC Search";
            case AC_HOME: "AC Home";
            case AC_BACK: "AC Back";
            case AC_FORWARD: "AC Forward";
            case AC_STOP: "AC Stop";
            case AC_REFRESH: "AC Refresh";
            case AC_BOOKMARKS: "AC Bookmarks";
            case SOFTLEFT: "Soft Left";
            case SOFTRIGHT: "Soft Right";
            case CALL: "Call";
            case ENDCALL: "End Call";
            //default: "Unknown (" + scancode + ")";
        }
    }
}